// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT65fCNHCOky3NqeDQpuVrzNb8DzcJ7gw',
    appId: '1:51707201292:web:c079f3df6641c44d82ab29',
    messagingSenderId: '51707201292',
    projectId: 'firestore-app-fdefb',
    authDomain: 'firestore-app-fdefb.firebaseapp.com',
    storageBucket: 'firestore-app-fdefb.appspot.com',
    measurementId: 'G-E3M3LB53QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJqZIymesYR-WejfQn9HmLPcKaAiTOLKo',
    appId: '1:51707201292:android:4fd698bafdfa8dea82ab29',
    messagingSenderId: '51707201292',
    projectId: 'firestore-app-fdefb',
    storageBucket: 'firestore-app-fdefb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUax5U1EO1dv7kS5B50EokFH0axbkt-JM',
    appId: '1:51707201292:ios:6dff9c88828da79682ab29',
    messagingSenderId: '51707201292',
    projectId: 'firestore-app-fdefb',
    storageBucket: 'firestore-app-fdefb.appspot.com',
    iosClientId: '51707201292-d5mcqhet7fesvkdth7ndbcm8och4qeiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUax5U1EO1dv7kS5B50EokFH0axbkt-JM',
    appId: '1:51707201292:ios:422aec1cd5f05c4382ab29',
    messagingSenderId: '51707201292',
    projectId: 'firestore-app-fdefb',
    storageBucket: 'firestore-app-fdefb.appspot.com',
    iosClientId: '51707201292-6gmmotcjprt0p1lm4uqe5tog3tb77g2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore2App.RunnerTests',
  );
}
